### ISSUE TITLE
test_voc.py fail

### ISSUE THREAD

**Issue by humm** [flowersteam/naminggamesal#1]
add() on a sparse matrix fails. 
```python
$ python test_voc.py
.E
======================================================================
ERROR: test_add_coherent (__main__.TestAdd)
Test that all implementations are coherent
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_voc.py", line 59, in test_add_coherent
    v.add(3, 4, 1)
  File "/Users/fabien/research/enc/coda/naminggamesal/lib/ngvoc/__init__.py", line 32, in mod_fun
    ans = tempfun(obj_self, *args)
  File "/Users/fabien/research/enc/coda/naminggamesal/lib/ngvoc/matrix.py", line 77, in add
    self._content[m,w] = val
  File "/Users/fabien/.pyenv/versions/2.7.6/lib/python2.7/site-packages/scipy/sparse/lil.py", line 286, in __setitem__
    i, j, x, self.dtype)
  File "_csparsetools.pyx", line 102, in scipy.sparse._csparsetools.lil_insert (scipy/sparse/_csparsetools.c:3424)
KeyError: dtype('float16')

----------------------------------------------------------------------
```

It seems due to this line:
https://github.com/flowersteam/naminggamesal/blob/c46cab903a35eaa4985234771dc3a3d47dd5d460/lib/ngvoc/matrix.py#L24

Is there a reason to use 'float16' explicitly ?

**Comment by wschuell** [comment]
J avais mis le float16 pour que ça prenne moins de place, vue qu il y a pas
besoin de grande précision. Moi j ai pas de souci, je pense que c est réglé
dans les versions récentes de numpy, dont la mienne
Le 6 sept. 2015 14:58, "Fabien Benureau" <notifications@github.com> a
écrit :

**Comment by humm** [comment]
Fails for me on both 1.9.0 et 1.9.2. Python version 2.7.6 on OS.X:
```
Python 2.7.6 (default, Mar 10 2014, 20:11:44)
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.2.79)] on darwin
```

**Comment by humm** [comment]
Was wrong, this line is the culprit:
https://github.com/flowersteam/naminggamesal/blob/c46cab903a35eaa4985234771dc3a3d47dd5d460/lib/ngvoc/matrix.py#L243

Changing it to:
```python
		self._content=sparse.lil_matrix((self._M,self._W))
```
solve the problem.
